### ISSUE TITLE
Kursutveckling inför vt19

### ISSUE THREAD

**Issue by AndreasArne** [dbwebb-se/oopython#11]
**Allmänt**
<s>- Fler exempel på UML diagram. Vi visar vad de ska göra eller hur det kan se ut.</s>
- Ett Flask spår igenom hela kursen? För nu får de 20p i proj för Flask, är det passande?
<s>- Hur lösa Fask på studentservern. Ta upp filer tidigare?</s>
<s>- Alternativ kursupplägg, mer som i boken - Introducera klassdiagram i kmom01 och använd igenom hela kursen eller bara ha med det från kmom01 och presentera officielt i kmom03?
    - Tror det hade hjälpt med klassdiagram från kmom01.</s>

**Kmom02**
- Ta upp överlagring/override.
<s>- Shapes uppgiften tyckte de var jätte svår.
    * De förstod delvis inte vad de skulle göra när de läste texten. Något saknas mellan övning och uppgift men svårt att se vad det skulle vara förutom att uppdatera uppgiftstexten.
    * Shape klassen bör vara ABC.
    * Läs redovisningtexter för mer info om vad som varr svårt med Shape.</s>
<s>- Klass relation artikel gå igenom ABC, Abstract base class.</s>
<s>- Övningen för post/form behöver vara grundligare och förklara koden mer.
    * Gör handler till en klass</s>

**Kmom03**
<s>- Lägg till create pil och self-calls i övning.
    * Uppdatera till snake_case istället för camelCase i diagram.</s>
<s>- De har svårt för sekvensdiagram. Föreläsningenvar förvirrande. Jobba mot kod nästa gång istället för text. Eller båda.
- Byt ut koden för sekvensuppgiften?</s>
<s>- I war uppgiften specifiera cad filen ska heta och lägga till viewContent i inspect.
    * Regler som säger mot varandra i olika länkar. Fastställ regler som gäller.
- De tycker kmom:et är stort, mycket att göra och gå igenom nya saker.</s>

**Kmom04**
- Skulle gissa på att många som inte har "korrekta" lösningar för många metoder i klasserna.

**Kmom05**
- I uppgifterna förtydliga att de ska jobba mot UnorderedList objekt och inte noder.

**Kmom06**
- Lägg till i test.py att det även ska fungera på `self.static = [3, -4, 6, 1, 1, -2, 2, 3]`. Nu går det att få rätt med en icke-komplett lösning. Hitta fler corner-cases. Kan ta upp som exempel i en föreläsning.
- Extra uppgift på nuvarande att det ska gå ännu snabbare?
- Mer/svårare uppgift - nuvarande uppgift gillas, lägg till mer kod.
    * https://www.codewars.com/kata/did-you-mean-dot-dot-dot. Möjlig vidare uppgift på nuvarande. Ska göra en ny version som hanterar strängar för att kolla vilket ord som är mest likt ett annat.
- Uppgift med träd/head?
- Mer om debuger?

**Kmom10**
- Få in datastruktur
- Flytta Binary search till grundkrav?
- Ska finnas både web och terminal interface. Men ska användas till olika saker. Ex en är admin interface och andra för kunder.
- Måste ha med tider i bokning. Jobba med datatime?
- 20p för Flask, är det passande?

**Comment by mosbth** [comment]
### Kursutvärdering 

Kursutvärderingen finns på http://bfm.bth.se/public/rapport/54cd0991-3357-429f-8bcf-52acd8aadf07

Snitt 3.18, 20 svarade av 58. Kursen gick för programstudenter Webbprogrammering på campus/distans.

**Comment by AndreasArne** [comment]
Angående friare krav på uppgifter var det något vi hade i kursen förra året men då var det inte uppskattat av studenterna och således skrotade vi de kraven till detta året. Det är inget vi kommer att införa igen då majoriteten av studenterna verkar inte uppskatta den typen av uppgifter.

Jag planerar på att lägga till mer UML och test exempel. Mer förklara hur man använder sig av tester.

Kmom02 finns på listan att göra om. Inte enbart pågrund av storleken på uppgiften men för att det ska fungera på studentservern. En tanke är att lägga till data till fil via terminalen som sen visas i webbläsare.

Vi har även pratat om att ha ett genomgående Flask tema i varje kmom. Probelemet med det är att uppgifterna blir genast svårare och tar längre tid att slutföra. Blir en balansgång för att få in det och fortfarande ha en lagom nivå på uppgifterna.

Kmom06 ska utökas, inte bestämt än om det ska läggas till extrauppgifter eller obligatoriska. Problemet med nuvarande uppgift är att den är antingen jättelätt eller jättesvår beroende om det klickar för studenten. En lösning kan vara att göra den till en obligatorisk gruppuppgift för att underlätta för de studenter som har väldigt svårt för uppgiften och då kan vi dessutom lägga in fler obligatoriska uppgifter. Då får även in sammarbete i kursen.

**Comment by AndreasArne** [comment]
<s>Kolla på video klipp om OO från Kommando. https://www.youtube.com/watch?v=xoL6WvCARJY</s>

**Comment by AndreasArne** [comment]
Träd i kmom06?

**Comment by AndreasArne** [comment]
Använd decorator för att ta tid på en functions exekvering. https://realpython.com/primer-on-python-decorators/#a-few-real-world-examples

**Comment by AndreasArne** [comment]
<s>Kmom01 guiden: Flytta privata attribut til kmom01 och överlagring till kmom02?</s>
Flyttat till VT20
