### ISSUE TITLE
Use virtual environment in the course

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/oopython#7]
Start using virtual environment when working on the course repo and figure out how this can/should affect how the students are working with the course material.

Perhaps they should work with it the same way. Support is already in the makefile.

The procedure is explained here:
https://dbwebb.se/forum/viewtopic.php?f=44&t=7008

If moving on with this, an article should be written, basically saying whats said in the forum topic.

**Comment by AndreasArne** [comment]
Implemented, https://dbwebb.se/kunskap/python-virtuel-miljo
