### ISSUE TITLE
Inspect on kmom01 behaving strangely

### ISSUE THREAD

**Issue by NiklasAurora** [dbwebb-se/oopython#9]
[dbwebb inspect oopython kmom01 isal17](https://gist.github.com/AuroraBTH/c6eaf618d3087152c486e45523dd168b) - When inspecting some students, no or less [errors](https://gist.github.com/AuroraBTH/c6eaf618d3087152c486e45523dd168b#file-dbwebb-inspect-oopython-kmom01-kinda-working-L148) are given.

[dbwebb inspect oopython kmom01 mabn17](https://gist.github.com/AuroraBTH/afb4f092c4cc5f4cdb9664c89ecf6cea) - Same issue as the one above but the error is given for each part of the inspect. The result is an 'dbwebb inspect' that don't ask if you want to inspect each part (as it should behave) but instead, it just continues until it's done.

The inspect seems to work without errors though, so this is no critical thing to fix.

**Comment by NiklasAurora** [comment]
Can confirm that the same issue occurs on kmom02.

**Comment by mosbth** [comment]
The problem occurs after the CSS-validator stylelint has run its first time. The validator makes something that corrupts the STDIN which gives the error message.

> read: read error: 0: Resource temporarily unavailable

[More details on this particular error situation](https://stackoverflow.com/questions/19895185/bash-shell-read-error-0-resource-temporarily-unavailable).

It is usually more error prone when running inspect through ssh on the studentserver (for this type of error), the same error may not show when running inspect locally.

I upgraded stylelint on ssh.student, but the error remains.

Quick workaround. Do local inspect in a local courserepo.

```
dbwebb --force download me $STUD
make inspect what=$KMOM
or
make inspect what=$KMOM options="--yes" > inspect.log
```

We should really do these local inspects within a docker container.

**Comment by mosbth** [comment]
I fixed a script to ease using local inspect. See https://github.com/dbwebb-se/oopython/blob/master/.dbwebb/script/inspect-local.bash

**Comment by NiklasAurora** [comment]
Issue seems to be fixed with the script provided (if you're not using WSL), more specific information available in comments to the [commit](https://github.com/dbwebb-se/oopython/commit/9a7f24911d37ae2e772038597c4f6fb0a94ac94e).

Script logs to file only and no print to terminal.
